apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-helloworlds
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-helloworlds
  template:
    metadata:
      labels:
        app: spring-helloworlds
    spec:
      containers:
      - image: jokersquotes.com/docker-registry/springapp
        imagePullPolicy: Always
        ports:
        - containerPort: 80
     

